### ISSUE TITLE
libtorch_cpu.so

### ISSUE THREAD

**Issue by wanglei1006** [yifita/deep_cage#14]
Dear yifita,
     when I run the cage_deformer_3d.py, the following Error arises.
---------
    from .._ext import sampling, linalg
ImportError: libtorch_cpu.so: cannot open shared object file: No such file or directory
----------
I searched for solutions and found that pytorch1.4.0 has no libtorch_cpu.so or libtorch_cuda.so, and it only has libtorch.so. 
While this code only works with pytorch1.4.0, I don't know how to solve this problem.
I appreciate your help, thanks a lot!

============================================================================
(pytorch-all2) wanglei@hmc46:/data2/wanglei/CG/deep_cage$ python cage_deformer_3d.py --dataset SHAPENET --full_net --bottleneck_size 256 --n_fold 2 --ckpt trained_models/chair_ablation_full/net_final.pth --target_model data/shapenet_target/**/*.obj  --source_model data/elaborated_chairs/throne_no_base.obj data/elaborated_chairs/Chaise_longue_noir_House_Doctor.ply --subdir fancy_chairs --phase test --is_poly
Traceback (most recent call last):
  File "cage_deformer_3d.py", line 14, in <module>
    from pytorch_points.network.geo_operations import mean_value_coordinates_3D, edge_vertex_indices
  File "/data2/wanglei/CG/deep_cage/pytorch_points/pytorch_points/network/geo_operations.py", line 4, in <module>
    from .operations import batch_svd, normalize, dot_product, scatter_add, faiss_knn, cross_product_2D, group_knn, gather_points
  File "/data2/wanglei/CG/deep_cage/pytorch_points/pytorch_points/network/operations.py", line 11, in <module>
    from .._ext import sampling, linalg
ImportError: libtorch_cpu.so: cannot open shared object file: No such file or directory

**Comment by cdjkim** [comment]
This could be the issue from having built with a different version of pytorch other than 1.4.0, the build folder in pytorch_points will have reminiscent of the legacy. Hence, try deleing the "build" folder and running `python setup.py develop` again.

**Comment by PengYicong** [comment]
> This could be the issue from having built with a different version of pytorch other than 1.4.0, the build folder in pytorch_points will have reminiscent of the legacy. Hence, try deleing the "build" folder and running `python setup.py develop` again.

solved this problem on my machine, thanks!
